services:
  db:
    build:
      context: ./holistic-faas-db
    container_name: holistic-faas-db
    image: holistic-faas-db:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: hf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  backend:
    build:
      context: ./holistic-faas-management-system
    container_name: holistic-faas-management-system
    image: holistic-faas-management-system:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hf
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      CORS_ALLOWED_ORIGINS: http://localhost:8081,http://localhost
    volumes:
      - uploads_volume:/app/uploads

  frontend:
    build:
      context: ./holistic-faas-ui
    container_name: holistic-faas-ui
    image: holistic-faas-ui:latest
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:8080/hf/api
      - VUE_APP_WS_BASE_URL=ws://localhost:8080/hf/ws
    ports:
      - "8081:80"

volumes:
  uploads_volume: